services:
  pravatv_speed:
    image: "docker.klik.cc/pravatv_speed:latest"
    ports:
      - "3000:3000"
    environment:
      # PORT: "3000"
      # LOG_LEVEL: "info"
      # DEFAULT_SIZE: "10485760"
      # MAX_DOWNLOAD: "104857600"
      # MAX_UPLOAD: "104857600"
